name: ci Tests - testHub

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [ test-results ]

jobs:
  trigger-tests:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger testHub Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TH_TOKEN_PAT }}
          repository: raymondskkb/test-hub
          event-type: run-tests
          client-payload: |
            {
              "project": "merchant-portal-ui-tests",
              "source_repo": "${{ github.repository }}",
              "source_run_id": "${{ github.run_id }}"
            }

  handle-test-result:
    if: github.event_name == 'repository_dispatch' && github.event.action == 'test-results'
    runs-on: ubuntu-latest
    steps:
      - name: Print test result
        run: |
          echo "Status: ${{ github.event.client_payload.status }}"
          echo "Run URL: ${{ github.event.client_payload.run_url }}"

      - name: Fail if tests failed
        if: ${{ github.event.client_payload.status != 'success' }}
        run: exit 1
