name: ci Tests - testHub

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [test-results]  # Listen for the test result notification from test-hub

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger testHub Workflow_Tests
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TH_TOKEN_PAT }}
          repository: raymondskkb/test-hub
          event-type: run-tests
          client-payload: '{"project":"merchant-portal-ui-tests"}'

  handle-test-result:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'repository_dispatch' && github.event.action == 'test-results' }}
    steps:
      - name: Print test result
        run: |
          echo "Test Result: ${{ github.event.client_payload.status }}"
          echo "Test Run URL: ${{ github.event.client_payload.run_url }}"
      - name: Fail if tests failed
        if: ${{ github.event.client_payload.status != 'success' }}  # If test status is not 'success', fail this job
        run: |
          echo "Tests failed! Check the details here: ${{ github.event.client_payload.run_url }}"
          exit 1
